/* 테이블 */
DROP TABLE BOARD_99 
	CASCADE CONSTRAINTS;

/* 테이블 */
CREATE TABLE BOARD_99 (
	SEQ NUMBER(7) NOT NULL, /* 순번 */
	TITLE VARCHAR2(300 CHAR) NOT NULL, /* 제목 */
	CONTENTS CLOB, /* 내용 */
	DIV VARCHAR2(2), /* 구분 */
	READ_CNT NUMBER(7) DEFAULT 0, /* 조회수 */
	REG_DT DATE DEFAULT SYSDATE, /* 등록일 */
	REG_ID VARCHAR2(20), /* 등록자 */
	MOD_DT DATE DEFAULT SYSDATE, /* 수정일 */
	MOD_ID VARCHAR2(20) /* 수정자 */
);

COMMENT ON TABLE BOARD_99 IS '테이블';

COMMENT ON COLUMN BOARD_99.SEQ IS '순번';

COMMENT ON COLUMN BOARD_99.TITLE IS '제목';

COMMENT ON COLUMN BOARD_99.CONTENTS IS '내용';

COMMENT ON COLUMN BOARD_99.DIV IS '구분';

COMMENT ON COLUMN BOARD_99.READ_CNT IS '조회수';

COMMENT ON COLUMN BOARD_99.REG_DT IS '등록일';

COMMENT ON COLUMN BOARD_99.REG_ID IS '등록자';

COMMENT ON COLUMN BOARD_99.MOD_DT IS '수정일';

COMMENT ON COLUMN BOARD_99.MOD_ID IS '수정자';

CREATE UNIQUE INDEX BOARD_99_PK
	ON BOARD_99 (
		SEQ ASC
	);

ALTER TABLE BOARD_99
	ADD
		CONSTRAINT BOARD_99_PK
		PRIMARY KEY (
			SEQ
		);