-- 기존 테이블 삭제, 제약조건
DROP TABLE NEW_TABLE 
	CASCADE CONSTRAINTS;

--테이블 생성
CREATE TABLE NEW_TABLE (
	NO NUMBER(3), /* 번호 */
	NAME VARCHAR2(10), /* 이름 */
	BIRTHDAY DATE /* 생년월일 */
);
--테이블 주석
COMMENT ON TABLE NEW_TABLE IS '새 테이블';
--컬럼 주
COMMENT ON COLUMN NEW_TABLE.NO IS '번호';

COMMENT ON COLUMN NEW_TABLE.NAME IS '이름';

COMMENT ON COLUMN NEW_TABLE.BIRTHDAY IS '생년월일';