/* 새 테이블3 */
DROP TABLE C_TEST1 
	CASCADE CONSTRAINTS;

/* 새 테이블4 */
DROP TABLE C_TEST2 
	CASCADE CONSTRAINTS;

/* 새 테이블3 */
CREATE TABLE C_TEST1 (
	NO NUMBER NOT NULL, /* 번호 */
	NAME VARCHAR2(10 CHAR), /* 이름 */
	DEPTNO NUMBER /* 부서 */
);

COMMENT ON TABLE C_TEST1 IS '새 테이블3';

COMMENT ON COLUMN C_TEST1.NO IS '번호';

COMMENT ON COLUMN C_TEST1.NAME IS '이름';

COMMENT ON COLUMN C_TEST1.DEPTNO IS '부서';

CREATE UNIQUE INDEX PK_C_TEST1
	ON C_TEST1 (
		NO ASC
	);

ALTER TABLE C_TEST1
	ADD
		CONSTRAINT PK_C_TEST1
		PRIMARY KEY (
			NO
		);

/* 새 테이블4 */
CREATE TABLE C_TEST2 (
	NO NUMBER NOT NULL, /* 번호 */
	NAME VARCHAR2(10 CHAR) /* 이름 */
);

COMMENT ON TABLE C_TEST2 IS '새 테이블4';

COMMENT ON COLUMN C_TEST2.NO IS '번호';

COMMENT ON COLUMN C_TEST2.NAME IS '이름';

CREATE UNIQUE INDEX PK_C_TEST2
	ON C_TEST2 (
		NO ASC
	);

CREATE UNIQUE INDEX UIX_C_TEST2
	ON C_TEST2 (
		NO ASC
	);

ALTER TABLE C_TEST2
	ADD
		CONSTRAINT PK_C_TEST2
		PRIMARY KEY (
			NO
		);

ALTER TABLE C_TEST2
	ADD
		CONSTRAINT UK_C_TEST2
		UNIQUE (
			NO
		);

ALTER TABLE C_TEST1
	ADD
		CONSTRAINT FK_C_TEST2_TO_C_TEST1
		FOREIGN KEY (
			DEPTNO
		)
		REFERENCES C_TEST2 (
			NO
		)ON DELETE SET NULL;