--INSERT INTO C_TEST2(NO,NAME) VALUES (10,'AAA');									
--INSERT INTO C_TEST2(NO,NAME) VALUES (20,'BBB');									
--INSERT INTO C_TEST2(NO,NAME) VALUES (30,'CCC');
--
--SELECT * FROM C_TEST2;

INSERT INTO C_TEST1(NO,NAME,NO2) VALUES(1,'AAA',10);
INSERT INTO C_TEST1(NO,NAME,NO2) VALUES(2,'BBB',20);
INSERT INTO C_TEST1(NO,NAME,NO2) VALUES(3,'CCC',30);

SELECT * FROM C_TEST1;