/* 새 테이블4 */
DROP TABLE C_TEST2 
	CASCADE CONSTRAINTS;

/* 새 테이블4 */
CREATE TABLE C_TEST2 (
	NO NUMBER, /* 번호 */
	NAME VARCHAR2(10 CHAR) /* 이름 */
);

COMMENT ON TABLE C_TEST2 IS '새 테이블4';

COMMENT ON COLUMN C_TEST2.NO IS '번호';

COMMENT ON COLUMN C_TEST2.NAME IS '이름';