/* 새 테이블3 */
DROP TABLE C_TEST1 
	CASCADE CONSTRAINTS;

/* 새 테이블3 */
CREATE TABLE C_TEST1 (
	NO NUMBER, /* 번호 */
	NAME VARCHAR2(10 CHAR), /* 이름 */
	DEPTNO NUMBER /* 부서번호 */
);

COMMENT ON TABLE C_TEST1 IS '새 테이블3';

COMMENT ON COLUMN C_TEST1.NO IS '번호';

COMMENT ON COLUMN C_TEST1.NAME IS '이름';

COMMENT ON COLUMN C_TEST1.DEPTNO IS '부서번호';