

/* 사원 */
DROP TABLE ED_EMP2 
	CASCADE CONSTRAINTS;

/* 사원 */
CREATE TABLE ED_EMP2 (
	EMP_NO NUMBER(4) NOT NULL, /* 사번 */
	NAME VARCHAR2(20 CHAR) NOT NULL, /* 이름 */
	JUMIN CHAR(13) NOT NULL, /* 주민번호 */
	LOC_CODE NUMBER(1), /* 지역코드 */
	DEPTNO VARCHAR2(6) /* 부서번호 */
);

COMMENT ON TABLE ED_EMP2 IS '사원';

COMMENT ON COLUMN ED_EMP2.EMP_NO IS '사번';

COMMENT ON COLUMN ED_EMP2.NAME IS '이름';

COMMENT ON COLUMN ED_EMP2.JUMIN IS '주민번호';

COMMENT ON COLUMN ED_EMP2.LOC_CODE IS '지역코드';

COMMENT ON COLUMN ED_EMP2.DEPTNO IS '부서번호';

CREATE UNIQUE INDEX PK_ED_EMP2
	ON ED_EMP2 (
		EMP_NO ASC
	);

CREATE UNIQUE INDEX UIX_ED_EMP2
	ON ED_EMP2 (
		JUMIN ASC
	);

ALTER TABLE ED_EMP2
	ADD
		CONSTRAINT PK_ED_EMP2
		PRIMARY KEY (
			EMP_NO
		);

ALTER TABLE ED_EMP2
	ADD
		CONSTRAINT UK_ED_EMP2
		UNIQUE (
			JUMIN
		);

ALTER TABLE ED_EMP2
	ADD
		CONSTRAINT CHK_ED_EMP2_LOC_CODE
		CHECK (LOC_CODE<5);

ALTER TABLE ED_EMP2
	ADD
		CONSTRAINT FK_ED_EMP2_TO_DEPT2
		FOREIGN KEY (
			DEPTNO
		)
		REFERENCES DEPT2 (
			DCODE
		);