DROP INDEX PK_EXMAPLE;

/* 테이블 설계 예시 */
DROP TABLE EXMAPLE 
	CASCADE CONSTRAINTS;

/* 테이블 설계 예시 */
CREATE TABLE EXMAPLE (
	ID NUMBER(5) NOT NULL, /* 아이디 */
	NAME VARCHAR2(8) NOT NULL, /* 이름 */
	BIRTH_DATE DATE, /* 생년월일 */
	SALARY NUMBER(9) DEFAULT 0, /* 급여 */
	PROFILE_JMG BLOB, /* 프로필_이미지 */
	REG_DATE DATE DEFAULT SYSDATE, /* 등록일 */
	REG_ID NUMBER(5), /* 등록자 */
	MOD_DATE DATE DEFAULT SYSDATE, /* 수정일 */
	MOD_ID NUMBER(5) /* 수정자 */
);

COMMENT ON TABLE EXMAPLE IS '테이블 설계 예시';

COMMENT ON COLUMN EXMAPLE.ID IS '아이디';

COMMENT ON COLUMN EXMAPLE.NAME IS '이름';

COMMENT ON COLUMN EXMAPLE.BIRTH_DATE IS '생년월일';

COMMENT ON COLUMN EXMAPLE.SALARY IS '급여';

COMMENT ON COLUMN EXMAPLE.PROFILE_JMG IS '프로필_이미지';

COMMENT ON COLUMN EXMAPLE.REG_DATE IS '등록일';

COMMENT ON COLUMN EXMAPLE.REG_ID IS '등록자';

COMMENT ON COLUMN EXMAPLE.MOD_DATE IS '수정일';

COMMENT ON COLUMN EXMAPLE.MOD_ID IS '수정자';

CREATE UNIQUE INDEX PK_EXMAPLE
	ON EXMAPLE (
		ID ASC
	);

ALTER TABLE EXMAPLE
	ADD
		CONSTRAINT PK_EXMAPLE
		PRIMARY KEY (
			ID
		);