DROP INDEX PK_ECAL;

/* 달력 */
DROP TABLE ECAL 
	CASCADE CONSTRAINTS;

/* 달력 */
CREATE TABLE ECAL (
	YEAR VARCHAR2(4) NOT NULL, /* 년도 */
	MONTH VARCHAR2(2) NOT NULL, /* 월 */
	DAYNO VARCHAR2(2) NOT NULL, /* 일 */
	WEEKNO VARCHAR2(1), /* 주 */
	DAY VARCHAR2(3), /* 요일 */
	REG_DT DATE DEFAULT SYSDATE, /* 등록일 */
	REG_ID VARCHAR2(20), /* 등록자 */
	MOD_DT DATE DEFAULT SYSDATE, /* 수정일 */
	MOD_ID VARCHAR2(20) /* 수정자 */
);

COMMENT ON TABLE ECAL IS '달력';

COMMENT ON COLUMN ECAL.YEAR IS '년도';

COMMENT ON COLUMN ECAL.MONTH IS '월';

COMMENT ON COLUMN ECAL.DAYNO IS '일';

COMMENT ON COLUMN ECAL.WEEKNO IS '주';

COMMENT ON COLUMN ECAL.DAY IS '요일';

COMMENT ON COLUMN ECAL.REG_DT IS '등록일';

COMMENT ON COLUMN ECAL.REG_ID IS '등록자';

COMMENT ON COLUMN ECAL.MOD_DT IS '수정일';

COMMENT ON COLUMN ECAL.MOD_ID IS '수정자';

CREATE UNIQUE INDEX PK_ECAL
	ON ECAL (
		YEAR ASC,
		MONTH ASC,
		DAYNO ASC
	);

ALTER TABLE ECAL
	ADD
		CONSTRAINT PK_ECAL
		PRIMARY KEY (
			YEAR,
			MONTH,
			DAYNO
		);