DROP INDEX PK_YEAR_MONTH;


/* 년도_월 */
CREATE TABLE YEAR_MONTH (
	YEAR CHAR(4) NOT NULL, /* 년도 */
	MONTH NUMBER(2) NOT NULL /* 월 */
);

COMMENT ON TABLE YEAR_MONTH IS '년도_월';

COMMENT ON COLUMN YEAR_MONTH.YEAR IS '년도';

COMMENT ON COLUMN YEAR_MONTH.MONTH IS '월';

CREATE UNIQUE INDEX PK_YEAR_MONTH
	ON YEAR_MONTH (
		YEAR ASC,
		MONTH ASC
	);

ALTER TABLE YEAR_MONTH
	ADD
		CONSTRAINT PK_YEAR_MONTH
		PRIMARY KEY (
			YEAR,
			MONTH
		);