

/* 공통코드 */
DROP TABLE COMMON_CODE 
	CASCADE CONSTRAINTS;

/* 공통코드 */
CREATE TABLE COMMON_CODE (
	CODE_GROUP VARCHAR2(50) NOT NULL, /* 코드그룹 */
	CODE VARCHAR2(50) NOT NULL, /* 코드 */
	CODE_NAME VARCHAR2(200) NOT NULL, /* 코드명 */
	USE_YN CHAR(1) DEFAULT 'Y', /* 사용여부 */
	SORT_ORDER NUMBER, /* 정렬순서 */
	REG_DT DATE DEFAULT SYSDATE, /* 등록일 */
	REG_ID VARCHAR2(20), /* 등록자 */
	MOD_DT DATE DEFAULT SYSDATE, /* 수정일 */
	MOD_ID VARCHAR2(20) /* 수정자 */
);

COMMENT ON TABLE COMMON_CODE IS '공통코드';

COMMENT ON COLUMN COMMON_CODE.CODE_GROUP IS '코드그룹';

COMMENT ON COLUMN COMMON_CODE.CODE IS '코드';

COMMENT ON COLUMN COMMON_CODE.CODE_NAME IS '코드명';

COMMENT ON COLUMN COMMON_CODE.USE_YN IS '사용여부';

COMMENT ON COLUMN COMMON_CODE.SORT_ORDER IS '정렬순서';

COMMENT ON COLUMN COMMON_CODE.REG_DT IS '등록일';

COMMENT ON COLUMN COMMON_CODE.REG_ID IS '등록자';

COMMENT ON COLUMN COMMON_CODE.MOD_DT IS '수정일';

COMMENT ON COLUMN COMMON_CODE.MOD_ID IS '수정자';

CREATE UNIQUE INDEX PK_COMMON_CODE
	ON COMMON_CODE (
		CODE_GROUP ASC,
		CODE ASC
	);

ALTER TABLE COMMON_CODE
	ADD
		CONSTRAINT PK_COMMON_CODE
		PRIMARY KEY (
			CODE_GROUP,
			CODE
		);